# Generated by Django 4.2.2 on 2023-06-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.IntegerField(choices=[(0, 'Saúde'), (1, 'Educação'), (2, 'Santuário'), (3, 'Ensino e Pesquisa'), (4, 'Sem preferência')], default=0)),
                ('data', models.DateTimeField(null=True)),
                ('tipo', models.IntegerField(choices=[(0, 'Financeiro'), (1, 'Bens Móveis ou Imóveis'), (2, 'Serviços'), (3, 'Produtos')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonimo', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0)),
                ('tipo_doador', models.IntegerField(choices=[(0, 'Pessoa Física'), (1, 'Pessoa Jurídica de Direito Privado'), (2, 'Pessoa Jurídica de Direito Público')], default=0)),
                ('pf_nome', models.CharField(max_length=200, null=True)),
                ('pf_cpf', models.IntegerField(null=True)),
                ('pf_dtnascimento', models.DateTimeField(null=True)),
                ('pf_telefone', models.CharField(max_length=20, null=True)),
                ('pj_desc', models.TextField(max_length=200, null=True)),
                ('pj_cnpj', models.CharField(max_length=200, null=True)),
                ('pj_email', models.EmailField(max_length=200, null=True)),
                ('pj_telefone', models.CharField(max_length=20, null=True)),
                ('pj_cidade', models.CharField(max_length=100, null=True)),
                ('lgpd', models.IntegerField(choices=[(0, 'Não Consentido'), (1, 'Consentido')], default=0)),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.IntegerField(choices=[(0, 'Especie'), (1, 'PIX'), (2, 'Cartão de Crédito'), (3, 'Cartão de Débito'), (4, 'Boleto'), (5, 'Transferência'), (6, 'Depósito'), (7, 'Conta de Energia'), (8, 'Incentivo')], default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doacao', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.doacao')),
            ],
        ),
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.doador'),
        ),
    ]
